const fs = require('fs');
const translate = require('translate-google')
const tranObj = {
    "language" : "English",
    "lanvalue" : "en",
    "login" : "LOGIN",
    "signup" : "SignUp",
    "forgotpasswordq" : "Forgot Password?",
    "nointernetconnection" : "No Internet Connection",
    "pleaseconnecttointernet" : "Please connect to the Internet!",
    "doesnthaveaccount" : "Does not have account?",
    "ok" : "OK",
    "usernotregistered" : "User Not Registered",
    "wrongpassword" : "Wrong Password",
    "loginsuccesful" : "Login Successfull",
    "passwordlabel" : "Password",
    "pleaseenterpassword" : "Please enter a Password",
    "passwordmustbe8long" : "Password must be at least 8 characters long",
    "phonenolabel" : "Phone Number",
    "phonenumberrequired" : "Phone number is required.",
    "pleaseentervalidphonenumber" : "Please enter a valid phone number.",
    "nextbutton" : "Next",
    "userexists" : "User Exists!",
    "waitforwhilesendingaotp" : "Wait for a while sending a otp!",
    "otphasbeensent" : "OTP has been sent.",
    "otpverify" : "OTP VERIFY",
    "otplabel" : "Enter OTP",
    "verifybutton" : "Verify",
    "phonenumberverified" : "Phone Number Verified",
    "wrongotp" : "Wrong OTP",
    "userdetails" : "USER DETAILS",
    "fullnamerequired" : "FullName is Required",
    "fullnamelabel" : "Full Name",
    "emaiisrequired" : "Email is required",
    "invalidemailaddress" : "Invalid Email Address",
    "emaillabel" : "Email",
    "bothpasswordsame" : "Both Password Must Be Same",
    "confirmpassword" : "Confirm Password",
    "save" : "Save",
    "useradded" : "User Added",
    "selectpicture" : "Select Picture",
    "camera" : "Camera",
    "gallery" : "Gallery",
    "removeprofile" : "Remove Profile",
    "upload" : "Upload",
    "skip" : "Skip",
    "usercreatedsuccessfully" : "User Created Successfully!",
    "requiredpassword" : "Password is required",
    "addjob" : "Add Job",
    "addjobmain" : "ADD JOB",
    "companynamerequired" : "Company Name is required",
    "companynamelabel" : "Company Name",
    "limitedcharacters" : "Limited Characters",
    "workisrequired" : "Work is required",
    "workjobtypelabel" : "Work(Job Type)",
    "addressisrequired" : "Address is required",
    "workaddress" : "Work Address",
    "chargestypelabel" : "Charges Type : ",
    "expectedsalaryisrequired" : "Expected Salary is required.",
    "expectedsalarylabel" : "Expected Given Salary",
    "updatework" : "Update Work",
    "removework" : "Remove Work",
    "workadded" : "Work Added",
    "workprofileupdated" : "Work Profile Updated",
    "workremovedsuccessfully" : "Work Removed Successfully",
    "addprofilemain" : "ADD PROFILE",
    "addworkingprofile" : "ADD WORKING PROFILE",
    "worktypeisrequired" : "Work Type is required",
    "worktypelabel" : "Work Type",
    "moneyneededisrequired" : "Money Needed is required.",
    "moneyneededlabel" : "Money Needed",
    "dob" : "Date Of Birth : ",
    "dobisrequired" : "DOB is required",
    "enterdatelabel" : "Enter Date : ",
    "gender" : "Gender : ",
    "addprofile" : "Add Profile",
    "updateprofile" : "Update Profile",
    "removeworkingprofile" : "Remove Working Profile",
    "userworkingprofileadded" : "User Working Profile Added",
    "userworkingprofileupdated" : "User Working Profile Updated",
    "profileremovedsuccessfully" : "Profile Removed Successfully",
    "developedby" : "Developed By",
    "allworkersmain" : "ALL WORKERS",
    "searchbyworkerswork" : "Search By Workers Work",
    "noworkersfound" : "No Workers Found",
    "work" : "WORK",
    "monthly" : "Monthly",
    "yearly" : "Yearly",
    "hourly" : "Hourly",
    "daily" : "Daily",
    "changepasswordmain" : "CHANGE PASSWORD",
    "changepasswordlabel" : "Change Password",
    "oldpassword" : "Old Password",
    "enternewpassword" : "Enter New Password",
    "userdeleted" : "User Deleted",
    "newpasswordlabel" : "New Password",
    "passwordmustbesame" : "Password Must Be Same",
    "alljobsmain" : "ALL JOBS",
    "searchbycompanywork" : "Search By Company Work",
    "nojobsfound" : "No Jobs Found",
    "sharejobdetails" : "Share Job Details",
    "company" : "Company",
    "jobprofilemain" : "JOB PROFILE",
    "charges" : "Charges",
    "shareworkerdetails" : "Share Worker Details",
    "workername" : "Worker Name",
    "workerprofilename" : "WORKER PROFILE",
    "pleaseselectprofilephoto" : "Please Select Profile Photo",
    "profileimageupdated" : "Profile Photo Updated",
    "editprofilemain" : "EDIT PROFILE",
    "selectimagehere" : "Select Image Here",
    "uploadphoto" : "Upload Photo",
    "userprofileupdated" : "User Profile Updated",
    "forgotpassword" : "Forgot Password",
    "setnewpassword" : "SET NEW PASSWORD",
    "updatepassword" : "Update Password",
    "passwordupdated" : "Password Updated",
    "needworkeraddjob" : "Need Worker? (Add Job)",
    "addworkingprofilen" : "Add Working Profile",
    "allworkersn" : "All Workers",
    "alljobsn" : "All Jobs",
    "editprofilen" : "Edit Profile",
    "changepasswordn" : "Change Password",
    "follow" : "Follow",
    "adminpannel" : "Admin Pannel",
    "settings" : "Settings",
    "logout" : "LogOut",
    "managejobs" : "MANAGE JOBS",
    "manageworkers" : "MANAGE WORKERS",
    "manageusers" : "MANAGE USERS",
    "workerremovedsuccessfully" : "Worker Removed Successfully",
    "searchbyname" : "Search By Name",
    "nouserfound" : "No Users Found",
    "userisadmin" : "User is Admin!",
    "userremovedsuccessfully" : "User Removed Successfully",
    "settingsmain" : "SETTINGS",
    "selectlanguage" : "SELECT LANGUAGE"
}

const translateString = async () => {
    return await translate(tranObj, {to: 'gu'})
}

const translator = async () =>  {
    let json = await translateString()
    json = JSON.stringify(json);

    fs.writeFile('output.json', json, err => {
        if (err) {
          console.error(err);
        } else {
          console.log('Data saved to file');
        }
      });
}

translator()